spring:
  application:
    name: TheDataBot
  datasource:
    hikari:
      maximum-pool-size: 10         # 最大连接数
      connection-timeout: 30000     # 连接超时，30秒
      idle-timeout: 600000          # 空闲连接在600秒（10分钟）后回收
      max-lifetime: 1800000         # 连接最大存活时间，1800秒（30分钟）
      validation-timeout: 5000      # 验证连接的超时时间，5秒
      connection-test-query: SELECT 1  # 用于验证连接的测试查询
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/sfsfsf  # 仅一个斜杠
          username: root
          password: 111111
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: org.thedatabot.thedatabot.entity
    global-config:
      db-config:
        id-type: ASSIGN_ID
        logic-delete-field: is_deleted
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      log-impl:

logging:
  level:
    org.mybatis: DEBUG  # 根据需要调整日志级别 (DEBUG, INFO, WARN, ERROR)
    com.baomidou.mybatisplus: DEBUG  # 如果使用 MyBatis-Plus
    org.thedatabot.thedatabot: DEBUG
