spring:
  application:
    name: TheDataBot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfsfsf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      filters: stat,wall,slf4j
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: org.thedatabot.thedatabot.entity
    global-config:
      db-config:
        id-type: ASSIGN_ID
        logic-delete-field: is_deleted
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      log-impl: org.apache.ibatis.logging.log4j2.Log4j2AbstractLoggerImpl

  #          # IP白名单
  #          allow: 127.0.0.1
  #          # IP黑名单（共同存在时，deny优先于allow）
  #          deny:
